server:
  port: 8081
  servlet:
    context-path: /userPortal
spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/employee
    username: root
    password: Root0
    driver-class-name :  com.mysql.jdbc.Driver
   
  mvc:
   view:
    prefix: /WEB-INF/pages/
    suffix: .jsp
   
